openreachtech/eslint-plugin-openreachtech

.npmrc, package-lock.json, package.json
* See #123
* Add `.npmrc`
* Update dependencies package versions to install `@openreachtech/eslint-config`
* Install `@openreachtech/eslint-config`
=> ⚙️ Install `@openreachtech/eslint-config`

.eslintrc.yml, tests/__tests__/empty-line-after-super.js, tests/__tests__/indent-in-infix-expression/logical-expression.js
=> ⚙️ Turn on ESLint rule `key-spacing`

.eslintrc.yml, lib/empty-line-after-super.js, lib/indent-in-infix-expression.js, lib/indent-in-infix-expression/IndentValidator.js, lib/no-comment-in-expression.js, lib/no-else-if.js, lib/no-if-in-oneline.js, lib/no-unexpected-multiline.js, lib/no-unexpected-multiline/LineBreakValidator.js, tests/tools/ESLintHelper.js
=> ⚙️ Turn on ESLint rule `jsdoc/tag-lines`

.eslintrc.yml, tests/__tests__/empty-line-after-super.js
=> ⚙️ Turn on ESLint rule `newline-per-chained-call`

.eslintrc.yml, lib/empty-line-after-super.js, lib/indent-in-infix-expression.js, lib/newline-per-parameter.js, lib/no-comment-in-expression.js, lib/no-if-in-oneline.js
=> ⚙️ Turn on ESLint rule `jsdoc/check-indentation`

.eslintrc.yml, tests/__tests__/indent-in-infix-expression/binary-expression.js, tests/__tests__/indent-in-infix-expression/logical-expression.js
=> ⚙️ Turn on ESLint rule `no-multiple-empty-lines`

.eslintrc.yml, tests/__tests__/no-comment-in-expression.js
=> ⚙️ Turn on ESLint rule `object-curly-spacing`

.eslintrc.yml, lib/no-comment-in-expression.js
=> ⚙️ Turn on ESLint rule `no-multi-spaces`

.eslintrc.yml, tests/__tests__/empty-line-after-super.js, tests/__tests__/no-comment-in-expression.js, tests/__tests__/no-if-in-oneline.js
=> ⚙️ Turn on ESLint rule `jest/valid-title`

.eslintrc.yml, lib/empty-line-after-super.js
=> ⚙️ Turn on ESLint rule `jsdoc/check-line-alignment`

.eslintrc.yml, lib/empty-line-after-super.js, tests/__tests__/no-else-if.js
=> ⚙️ Turn on ESLint rule `prefer-destructuring`

lib/indent-in-infix-expression/IndentValidator.js, tests/__tests__/indent-in-infix-expression/logical-expression.js
=> 🐛 Fix `indent-in-infix-expression`

.gitignore, .vscode/cspell.json
=> ⚙️ Add `.vscode/cspell.json`

lib/empty-line-after-super.js, lib/indent-in-infix-expression/IndentValidator.js, lib/no-comment-in-expression.js, lib/no-if-in-oneline.js, lib/no-unexpected-multiline/LineBreakValidator.js
=> 💪 Replace duplicated method of ESLint

tests/__tests__/empty-line-after-super.js, tests/__tests__/no-if-in-oneline.js
=> 🧹 Remove trailing spaces

tests/__tests__/indent-in-infix-expression/logical-expression.js
=> ⚒ Add test for `indent-in-infix-expression`

package.json
=> ⚙️ Add shorthand script `l` to `package.json`

package-lock.json, package.json
=> ⚙️ Update package version to `1.0.0`

package-lock.json, package.json
=> ⚙️ Update package of `@openreachtech/eslint-config`

.eslintrc.yml
=> ⚙️ Turn on ESLint rule `openreachtech/indent-in-infix-expression`

.eslintrc.yml, package-lock.json, package.json
* Close #174
* Published codes have not changed, thus merge to `main` only with no version up package
=> Release > Main

.eslintrc.yml, package-lock.json, package.json
* Close #144
* All commits have aleady been reviewed, merge only
=> ⚙️ Update `.eslintrc.yml` to turn on ESLint rule `openreachtech/indent-in-infix-expression`

lib/indent-in-infix-expression/IndentValidator.js, tests/__tests__/indent-in-infix-expression/logical-expression.js
=> 🐛 Fix `indent-in-infix-expression` rule

.vscode/cspell.json, tests/__tests__/no-else-if.js
* Close #193
* Add `estree` to `.vscode/cspell.json`
* Rename `subconditions` to `secondCondition`
=> ⚙️ Update `.vscode/cspell.json`
